<!DOCTYPE html>
<html>
<head>
	<title>Timetable</title>
</head>
<body>
	<table style="width:100%">
		<tr>
			<th>Monday</th>
			<th>Tuesday</th> 
			<th>Wednesday</th>
			<th>Thursday</th>
			<th>Friday</th>
		</tr>
		<tr>
			<td>Placeholder</td>
			<td>Placeholder</td> 
			<td>Placeholder</td>
			<td>Placeholder</td>
			<td>Placeholder</td>
		</tr>
		<tr>
			<td>Placeholder</td>
			<td>Placeholder</td> 
			<td>Placeholder</td>
			<td>Placeholder</td>
			<td>Placeholder</td>
		</tr>
	</table>
</body>
</html>